// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionalManagement.Models;

namespace SessionalManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251004121920_BCryptedPass")]
    partial class BCryptedPass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SessionalManagement.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Sessional 1",
                            Semester = 5
                        },
                        new
                        {
                            Id = -2,
                            Name = "Sessional 2",
                            Semester = 5
                        },
                        new
                        {
                            Id = -3,
                            Name = "Sessional 3",
                            Semester = 5
                        });
                });

            modelBuilder.Entity("SessionalManagement.Models.Marks", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("MarksObtained")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "ExamId", "SubjectId");

                    b.HasIndex("ExamId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Marks");

                    b.HasData(
                        new
                        {
                            StudentId = -1,
                            ExamId = -1,
                            SubjectId = -1,
                            MarksObtained = 30
                        },
                        new
                        {
                            StudentId = -1,
                            ExamId = -1,
                            SubjectId = -2,
                            MarksObtained = 32
                        },
                        new
                        {
                            StudentId = -1,
                            ExamId = -1,
                            SubjectId = -3,
                            MarksObtained = 31
                        },
                        new
                        {
                            StudentId = -2,
                            ExamId = -1,
                            SubjectId = -1,
                            MarksObtained = 29
                        },
                        new
                        {
                            StudentId = -2,
                            ExamId = -1,
                            SubjectId = -2,
                            MarksObtained = 33
                        },
                        new
                        {
                            StudentId = -2,
                            ExamId = -1,
                            SubjectId = -3,
                            MarksObtained = 31
                        },
                        new
                        {
                            StudentId = -3,
                            ExamId = -1,
                            SubjectId = -1,
                            MarksObtained = 27
                        },
                        new
                        {
                            StudentId = -3,
                            ExamId = -1,
                            SubjectId = -2,
                            MarksObtained = 34
                        },
                        new
                        {
                            StudentId = -3,
                            ExamId = -1,
                            SubjectId = -3,
                            MarksObtained = 35
                        });
                });

            modelBuilder.Entity("SessionalManagement.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Web Application Developement(WAD)",
                            Semester = 5
                        },
                        new
                        {
                            Id = -2,
                            Name = "Advanced Technologies(AT)",
                            Semester = 5
                        },
                        new
                        {
                            Id = -3,
                            Name = "Operating System",
                            Semester = 5
                        });
                });

            modelBuilder.Entity("SessionalManagement.Models.TeacherSubjects", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            TeacherId = -4,
                            SubjectId = -1
                        },
                        new
                        {
                            TeacherId = -5,
                            SubjectId = -2
                        },
                        new
                        {
                            TeacherId = -5,
                            SubjectId = -3
                        });
                });

            modelBuilder.Entity("SessionalManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("SessionalManagement.Models.Student", b =>
                {
                    b.HasBaseType("SessionalManagement.Models.User");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "student001@ddu.ac.in",
                            Name = "Mohit Gajjar",
                            Password = "$2a$11$msM8vgUX5/QaMQ0L09t0T.gpUPHkBFJ/rfYCty1iwAb9MJmOudVhu",
                            Role = 0,
                            Semester = 5
                        },
                        new
                        {
                            Id = -2,
                            Email = "student002@ddu.ac.in",
                            Name = "Kavan Dave",
                            Password = "$2a$11$yn0ZmxludgxDDqaktwgToOTKZ9xniVW/Lbqd/gemZGPwe/3miI/xq",
                            Role = 0,
                            Semester = 5
                        },
                        new
                        {
                            Id = -3,
                            Email = "student003@ddu.ac.in",
                            Name = "Vismay Chaudhari",
                            Password = "$2a$11$ja5LU/B.9HcRE2PNBF/AB.1EPqbjsSc/0mvIHGk/tM7T7u0Vmqpva",
                            Role = 0,
                            Semester = 5
                        });
                });

            modelBuilder.Entity("SessionalManagement.Models.Teacher", b =>
                {
                    b.HasBaseType("SessionalManagement.Models.User");

                    b.HasDiscriminator().HasValue("Teacher");

                    b.HasData(
                        new
                        {
                            Id = -4,
                            Email = "faculty001@ddu.ac.in",
                            Name = "AAM",
                            Password = "$2a$11$qGWbhdZ3mGuODeKGYL7hQOmk4/rT8kZjbFEljFcu.Ta6u97dVBE7G",
                            Role = 1
                        },
                        new
                        {
                            Id = -5,
                            Email = "faculty002@ddu.ac.in",
                            Name = "SPS",
                            Password = "$2a$11$BfwbBLU1bg9E9qDk1TjjhO3eETjuq3kK.Bp52peXg56vrMxsX7/HO",
                            Role = 1
                        });
                });

            modelBuilder.Entity("SessionalManagement.Models.Marks", b =>
                {
                    b.HasOne("SessionalManagement.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionalManagement.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionalManagement.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SessionalManagement.Models.TeacherSubjects", b =>
                {
                    b.HasOne("SessionalManagement.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionalManagement.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
